---
title: "DM_Group_30"
output: html_document
date: "2024-03-05"
---

```{r setup, include=FALSE}
library(readr)
library(RSQLite)
library(dplyr)
```

```{r}
my_connection <- RSQLite::dbConnect(RSQLite::SQLite(),"database.db")
```

# Loading data
```{r dataloading,message=FALSE,warning=FALSE}
Customer <- readr::read_csv("data_upload/customer.csv")
Product <- readr::read_csv("data_upload/product.csv")
Supplier <- readr::read_csv("data_upload/supplier.csv")
Warehouse <- readr::read_csv("data_upload/warehouse.csv")

```

# Write them to the database 
```{r writebacktodb}
RSQLite::dbWriteTable(my_connection,"Customer",Customer,overwrite=TRUE)
RSQLite::dbWriteTable(my_connection,"Product",Product,overwrite=TRUE)
RSQLite::dbWriteTable(my_connection,"Supplier",Supplier,overwrite=TRUE)
RSQLite::dbWriteTable(my_connection,"Warehouse",Warehouse,overwrite=TRUE)

```

```{r writebacktodb}
RSQLite::dbExecute(my_connection, "DROP TABLE IF EXISTS Category")

RSQLite::dbExecute(my_connection, "
  CREATE TABLE Category (
    category_id VARCHAR(5) PRIMARY KEY,
    category_name VARCHAR(50),
    parent_category_id VARCHAR(5),
    parent_category_name VARCHAR(255)
  )
")
```
```{r}
RSQLite::dbExecute(my_connection, "
  INSERT INTO Category (category_id, category_name, parent_category_id, parent_category_name)
VALUES
  ('c1', 'Butter', 'pc1', 'Daily_Products'),
  ('c2', 'Cheese', 'pc1', 'Daily_Products'),
  ('c3', 'Egg', 'pc1', 'Daily_Products'),
  ('c4', 'Milk', 'pc1', 'Daily_Products'),
  ('c5', 'Alcohol', 'pc2', 'Drinks'),
  ('c6', 'Coffee', 'pc2', 'Drinks'),
  ('c7', 'Juices', 'pc2', 'Drinks'),
  ('c8', 'Soft_Drinks', 'pc2', 'Drinks'),
  ('c9', 'Water', 'pc2', 'Drinks'),
  ('c10', 'Fruits', 'pc3', 'Fresh_Products'),
  ('c11', 'Herbs', 'pc3', 'Fresh_Products'),
  ('c12', 'Vegetables', 'pc3', 'Fresh_Products'),
  ('c13', 'Beef', 'pc4', 'Meat'),
  ('c14', 'Chicken', 'pc4', 'Meat'),
  ('c15', 'Pork', 'pc4', 'Meat'),
  ('c16', 'Shrimp', 'pc4', 'Meat'),
  ('c17', 'Candy', 'pc5', 'Snacks'),
  ('c18', 'Chips', 'pc5', 'Snacks'),
  ('c19', 'Chocolate', 'pc5', 'Snacks'),
  ('c20', 'Nuts', 'pc5', 'Snacks');
")

```

```{sql connection=my_connection}
select * from Category
```

```{r}
RSQLite::dbExecute(my_connection, "
  ALTER TABLE Product
  ADD COLUMN category_id VARCHAR(5);
")
```

```{r}
RSQLite::dbExecute(my_connection, "
  UPDATE Product
  SET category_id = (
    CASE
      WHen product_name IN ('Salted Butter (Land OLakes)','Unsalted Butter (Kerrygold)','Clarified Butter (Ghee Easy)','European Style Butter (Plugrá)') Then 'c1'
      
      WHen product_name IN ('Cheddar Cheese (Tillamook)','Mozzarella Cheese (Galbani)','Swiss Cheese (Emmi)','Pepper Jack Cheese (Tillamook)') Then 'c2'
      
      WHen product_name IN ('Large Eggs (Organic Valley)','Brown Eggs (Happy Egg Co.)','Free-range Eggs (Vital Farms)','Organic Eggs (Egglands Best)') Then 'c3'
      
      WHen product_name IN ('2% Milk (Horizon)','Almond Milk (Silk)','Soy Milk (Silk)','Whole Milk (Organic Valley)') Then 'c4'
      
      WHEN product_name IN ('Beer (Budweiser)', 'Wine (Cabernet Sauvignon)', 'Vodka (Smirnoff)','Whiskey (Jack Daniels)') THEN 'c5'
      
      WHEN product_name IN ('Arabica Coffee Beans (Starbucks)','Espresso Ground Coffee (Lavazza)','French Roast Coffee (Peets Coffee)','Decaf Coffee (Folgers)') Then 'c6'
      
      WHEN product_name IN ('Apple Juice (Minute Maid)','Cranberry Juice (Ocean Spray)','Orange Juice (Tropicana)','Pineapple Juice (Dole)') Then 'c7'
      
      WHEN product_name IN ('Cola (Coca-Cola)','Ginger Ale (Canada Dry)','Lemon-Lime Soda (Sprite)','Root Beer (A&W)') Then 'c8'
      
      WHEN product_name IN ('Bottled Water (Spring Water)','Flavored Water (Hint Water)','Sparkling Water (Perrier)','Spring Water (Evian)') Then 'c9'
      
      WHen product_name IN ('Apple (Red Delicious)','Banana (Cavendish)','Orange (Navel)','Strawberry (Sweet Charlie)') Then 'c10'
      
      WHen product_name IN ('Basil (Genovese)','Parsley (Italian Flat-leaf)','Mint (Spearmint)','Rosemary (Common)') Then 'c11'
      
      WHEN product_name IN ('Broccoli (Calabrese)','Carrot (Nantes)','Spinach (Baby Leaf)','Tomato (Beefsteak)') Then 'c12'
      
      WHEN product_name IN ('Ribeye Steak (Prime Grade)','Ground Beef (80/20 Lean to Fat Ratio)','Beef Tenderloin (Filet Mignon)','Beef Brisket (Whole, Untrimmed)') Then 'c13'
      
      WHEN product_name IN ('Chicken Breast (Boneless, Skinless)','Chicken Thighs (Bone-In, Skin-On)','Chicken Wings (Party Style)','Whole Chicken (Free-Range)') Then 'c14'
      
      WHEN product_name IN ('Ham (Smoked, Bone-In)','Pork Belly (Skin-On)','Pork Chops (Bone-In)','Pork Tenderloin (Center-Cut)') Then 'c15'
      
      WHEN product_name IN ('Black Tiger Shrimp (Large, Head-On)','Jumbo Shrimp (Peeled, Deveined)','Tiger Shrimp (Wild-Caught)','White Shrimp (Farm-Raised)') Then 'c16'
      
      WHEN product_name IN ('Gummy Bears (Assorted Flavors)','Mint Candy (Deep Blue)','Sour Patch Kids (Original)','Licorice (Red Twists)') Then 'c17'
      
      WHEN product_name IN ('Potato Chips (Classic Salted)','Tortilla Chips (Restaurant Style)','BBQ Chips (Hickory Smoked)','Salt & Vinegar Chips (Kettle Cooked)') Then 'c18'
      
      WHEN product_name IN ('Milk Chocolate Bar (Hersheys)','Dark Chocolate Bar (Lindt Excellence)','Chocolate Covered Almonds (Blue Diamond)','Chocolate Truffles (Godiva)') Then 'c19'
      
      ELSE 'c20'
  
    END
)
")

```

```{r}
RSQLite::dbExecute(my_connection, "
  CREATE TABLE Product_New AS
  SELECT * FROM Product;

  DROP TABLE Product;

  ALTER TABLE Product_New
  RENAME TO Product;

  ALTER TABLE Product
  ADD FOREIGN KEY (category_id) REFERENCES Category(category_id);
")
```
```{sql connection=my_connection}
select * from Product
```

