name: Assignment

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/lockfile') }}
          restore-keys: |
            ${{ runner.os }}-r-
      - name: Install pandoc
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e 'install.packages(c("RSQLite","readr","dplyr","rmarkdown","knitr","readxl","openxlsx","ggplot2","scales"))'
      - name: Data Validation and Insertion
        run: |
          Rscript R/Data_Validation_and_Insertion.R
      - name: Data Analysis
        run: |
          Rscript R/Data_Analysis.R
      - name: Add files
        run: |
          git config --global user.email "bellyzhang0306@outlook.com"
          git config --global user.name "YiZhang2001"
          git add Database/database.db
          git add Analysis_Results/*.xlsx
          git add analysis_graphs/*.png
      - name: Commit files
        run: |
          git commit -m "Run the latest Rscritp"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
            github_token: ${{ secrets.PAT }}
            branch: main